apiVersion: apps/v1
kind: Deployment
metadata:
  name: jollfi-gaming-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jollfi-gaming-api
  template:
    metadata:
      labels:
        app: jollfi-gaming-api
    spec:
      containers:
        - name: jollfi-gaming-api
          image: jollfi-gaming-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: uri
            - name: SUI_NETWORK_URL
              value: "https://fullnode.testnet.sui.io:443"
            - name: SUI_PACKAGE_ID
              valueFrom:
                secretKeyRef:
                  name: sui-secret
                  key: package_id
            - name: SUI_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: sui-secret
                  key: pool_id
            - name: SUI_MODULE_NAME
              value: "jollfi_wallet"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt
            - name: LOG_LEVEL
              value: "info"
            - name: SUI_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: sui-secret
                  key: private_key