apiVersion: v1
kind: Service
metadata:
  name: jollfi-gaming-api-service
spec:
  selector:
    app: jollfi-gaming-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP