name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./internal/tests/...

      - name: Build Docker image
        run: docker build -t jollfi-gaming-api:latest .

      - name: Dummy deployment
        run: echo "Deploying to dummy environment at https://dummy-jollfi-gaming-api.com"